server:
  port: 10001
spring:
  application:
    name: server-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # alibaba在2020版本之后不使用ribbon，这里使用loadbalancer代替，在配置文件中禁用ribbon
    loadbalancer:
      ribbon:
        enable: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-gateway
          uri: lb://server-user
          order: 1
          predicates:
            - Path=/server-user/**
          filters:
            - StripPrefix=1

        - id: data-gateway
          uri: lb://server-data
          order: 1
          predicates:
            - Path=/server-data/**
          filters:
            - StripPrefix=1

        - id: camunda-gateway
          uri: lb://server-camunda
          order: 1
          predicates:
            - Path=/server-camunda/**
          filters:
            - StripPrefix=1