server:
  port: 5000
spring:
  application:
    name: springcloud-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
      instance-id: ${spring.application.name}:${random.int}
logging:
  level: info
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%level] [%thread] [%logger] >>> %msg%n"
zuul:
  routes:
    service-consumer-api:
      path: /service-consumer/**
      serviceId: springcloud-rest-consumer
  ignored-patterns: /**/testurl/**     #过滤匹配,匹配上的请求不做路由转发
##########################################################################################################
#zuul:
#  routes:
#    service-consumer-api:
#      path: /service-consumer/**
#      serviceId: microservice-feign-consumer
#    service-local-api:
#      path: /service-local/**
#      url: forward:/local
#  ignored-patterns: /**/testurl/** #过滤匹配,匹配上的请求不做路由转发
#  add-host-header: true #路由转发前设置HOST头信息
#  retryable: false #关闭重试机制
#  servlet-path: /zuul/* #设置请求路径绕过spring DispatchServlet,使用ZuulServlet处理