server:
  port: 8081

baserpc:
  sunny:
    consumer:
      # zookeeper server
      registryAddress: 192.168.184.102:2181
      # registry center type, zookeeper/nacos/apoll/etcd/eureka
      registryType: zookeeper
      # registry loadbalance type: zkconsistenthash
      loadBalanceType: zkconsistenthash
      # proxy type/javassist/jdk
      proxy: asm
      # version
      version: 1.0.0
      # group
      group: SUNNY
      # zkconsistenthash
      serializationType: protostuff
      # timeout
      timeout: 30000
      # async
      async: false
      # oneway
      oneway: false
      # heartbeatInterval
      heartbeatInterval: 30000
      # scanNotActiveChannelInterval
      scanNotActiveChannelInterval: 60000
      # retryInterval
      retryInterval: 1000
      # retryTimes
      retryTimes: 3

