server:
  port: 9000
  servlet:
#    context-path: /middle
    session:
      timeout: 1800 # 会话超时时间（秒）
    # https配置
    # 证书命令：keytool -genkey -alias webhttps -keyalg RSA -keysize 2048 -keystore sang.p12 -validity 365
#  ssl:
#    key-store: sang.p12 # 保存到根目录
#    key-alias: webhttps
#    key-store-password: 123456

spring:
  application:
    name: middle-server
  thymeleaf:
    # 是否开启缓存，开发时可设置为 false ，默认为 true
    cache: false
    # 检查模板是否存在，默认为 true
    check-template: true
    # 检查模板位置是否存在，默认为 true
    check-template-location: true
    # 模板文件编码
    encoding: UTF-8
    # 模板文件位置
    prefix: classpath:/templates/
    # Content Type 配置
    servlet:
      content-type: text/html
    # 模板文件后缀
    suffix: .html
  servlet:
    # 附件上传设置
    multipart:
      enabled: true
      file-size-threshold: 0
      location: E:\\tmp
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false
  redis:
    database: 15
    host: 192.168.100.148
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher