server:
  port: 8761

spring:
  application:
    name: @pom.artifactId@

eureka:
  server:
    #eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，
    #过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
    #默认180s
    response-cache-auto-expiration-in-seconds: 180
    #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，
    #这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    #默认30s
    response-cache-update-interval-ms: 3000
    enable-self-preservation: false # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 5000 # 清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 服务为注册中心，所以不需要注册自己，设置false
    fetch-registry: false # 设置false，不去检索服务