server:
  port: 8000
###使用druid数据源
spring:
  application:
    name: springcloud-rest-provider
  datasource:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    druid:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:liuty
      username: sa
      password:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000 #每60秒运行一次空闲连接回收器
      min-evictable-idle-time-millis: 300000 #池中的连接空闲5分钟后被回收
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: conn,stat,wall,log4j #启用过滤器，stat:监控统计过滤器;wall:防注入过滤器;log4j:日志过滤器;
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev  #设置开发模式，加载下面开发模式的配置
###启用监控模块
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "*"
####################################[eureka注册客户端配置]##################################
eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      zone: beijing

---
##开发环境
spring:
  profiles: dev

mytest:
  name: dev
  value: dev@qq.com

---
##测试环境
spring:
  profiles: test

mytest:
  name: test
  value: test@qq.com
####################################[Spring Boot 日志配置]##################################
#logging:
#  level: info
#  pattern:
#    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%level] [%thread] [%logger] >>> %msg%n"
####################################[eureka注册客户端配置]##################################
#eureka:
#  instance:
#    metadata-map:
#      my-metadata: 自定义元数据
#      zone: test1
####################################[eureka集群连接配置]##################################
#eureka:
#  client:
#    service-url:
#      default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
#####################################[多数据源配置信息]##################################
###one datasource
#foo:
#  datasource:
#    url: jdbc:h2:mem:foo
#    username: sa
#    password:
###second datasource
#bar:
#  datasource:
#    url: jdbc:h2:mem:bar
#    username: sa
#    password: