server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jap:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.3.6:1521:orcl
    username: pay_lhc170119
    password: 1
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasiceExtractor: TRACE
eureka:
  client:
    service-url:
      #default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/   高可用注册中心配置
      #defaultZone: http://user:password123@localhost:8761/eureka/    #使用用户名、密码注册注册中心
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    # 自定义元数据
    metadata-map:
      my-metadata: 自定义元数据
    ip-address: localhost   # 绑定注册地址