server:
  port: 8072

servicecomb:
  service:
    application: demo-application
    name: web-service
    version: 0.0.1
    registry:
      # Default using local service center
      address: http://127.0.0.1:30100
      instance:
        watch: false
  rest:
    address: 0.0.0.0:8072
  inspector:
    enabled: false


