server:
  port: 7001
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ltybjeagle/project-ltydemo
          search-paths: project-manager/project-register-eureka
          username:
          password: