spring:
  application:
    name: portal-service
  profiles:
    active: eureka
server:
  port: 8082
logging:
  level:
    com:
      sunny:
        maven:
          feign:
            client: DEBUG # feign调用日志
#feign 使用 okhttp
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
#  # 配置 GZIP 来压缩数据，没有启用 okhttp3 时才会进行压缩配置
#  compression:
#    request:
#      enabled: true
#      # 配置压缩的类型、最小压缩值的标准
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true