server:
  port: 8050
  servlet:
    context-path: /middle

spring:
  application:
    name: microservice-middle
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@192.168.100.80:1521/orcl
      username: fasp_34dev
      password: 1
      driver-class-name: oracle.jdbc.OracleDriver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 3600000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 3600000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,slf4j
      filter:
        stat:
          enabled: true          # 开启DruidDataSource状态监控
          db-type: oracle        # 数据库的类型
          log-slow-sql: true     # 开启慢SQL记录功能
          slow-sql-millis: 2000  # 默认3000毫秒，这里超过2s，就是慢，记录到日志
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置 DruidStatFilter
      ########## 配置WebStatFilter，用于采集web关联监控的数据 ##########
      web-stat-filter:
        enabled: true                # 启动 StatFilter
        url-pattern: /*              # 过滤所有url
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*   # 排除一些不必要的url
        session-stat-enable: "true"    # 开启session统计功能
        session-stat-max-count: "1000" # session的最大个数,默认100
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
        deny: 192.168.31.253
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: root
        login-password: 123456
        # 需要设置enabled=true,否则会报出There was an unexpected error (type=Not Found, status=404).错误，
        # 或者将druid-spring-boot-starter的版本降低到1.1.10及以下
        # 是否启用StatViewServlet（监控页面）默认值为false
        # （考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        enabled: true
      aop-patterns: "com.springboot.template.dao.*"

http:
  encoding:
    enabled: true
    charset: UTF-8
    force: true