server:
  port: 8080

baserpc:
  sunny:
    provider:
      # rpc server
      serverAddress: 0.0.0.0:20881
      # serverRegistryAddress
      serverRegistryAddress: 192.168.184.102:20881
      # zookeeper server
      registryAddress: 192.168.184.102:2181
      # registry center type, zookeeper/nacos/apoll/etcd/eureka
      registryType: zookeeper
      #registry loadbalance type: zkconsistenthash
      registryLoadBalancerType: zkconsistenthash
      # reflect type, value is jdk or cglib
      reflectType: asm
      # heartbeatInterval
      heartbeatInterval: 30000
      # scanNotActiveChannelInterval
      scanNotActiveChannelInterval: 60000

