server:
  port: 8080

spring:
  application:
    name: @pom.artifactId@
  cloud:
    gateway:
      routes:
      - id: url-proxy-echo
        uri: lb://platform-springcloud-consumer
        predicates:
        - Path=/echo-rest/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    registry-fetch-interval-seconds: 30 # 拉取注册中心数据间隔时间
    serviceUrl:
      defaultZone: http://sunny:123456@localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90