server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true #从注册中心拉去服务清单
    registry-fetch-interval-seconds: 30 #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true  #开启ribbon重试
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  ConnectTimeout: 250 #请求连接的超时时间
  ReadTimeout: 1000 #请求处理的超时时间
  OkToRetryOnAllOperations: true #对所有请求进行重试
  MaxAutoRetriesNextServer: 2 #切换其他实例重试次数
  MaxAutoRetries: 1 #同一实例重试次数
#logging:
#  level:
#    com.liuty.maven.feignclient.DemoUserFeignClient: DEBUG
#feign:
#  hystrix:
#    enabled: true