spring:
  application:
    name: springcloud-rest-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启ribbon重试
server:
  port: 9000
####################################[eureka注册客户端配置]##################################
eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      zone: beijing
feign:
  hystrix:
    enabled: true #开启熔断器
  compression: #开启请求、响应GZIP压缩
    request:
      enabled: true
      mime-types: ["text/xml", "application/xml", "application/json"]   #压缩类型
      min-request-size: 2048    #超过设置大小的进行压缩
    response:
      enabled: true
############################################################################################
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 9000