spring:
  application:
    name: springcloud-rest-consumer
server:
  port: 9000
####################################[eureka注册客户端配置]##################################
eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${random.int}
############################################################################################
#spring:
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: true  #开启ribbon重试
#  application:
#    name: microservice-feign-consumer
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#  ConnectTimeout: 500 #请求连接的超时时间
#  ReadTimeout: 3000 #请求处理的超时时间
#  OkToRetryOnAllOperations: true #对所有请求进行重试
#  MaxAutoRetriesNextServer: 2 #切换其他实例重试次数
#  MaxAutoRetries: 1 #同一实例重试次数
#feign:
#  hystrix:
#    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 9000
#logging:
#  level:
#    com.liuty.maven.service.feign.UserFeignClient: debug