server:
  port: 8080
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
logging:
  level:
    com.liuty.maven.feignclient.DemoUserFeignClient: DEBUG