server:
  port: 10000
spring:
  application:
    name: server-gateway
  main:
    allow-bean-definition-overriding: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"