server:
  port: 6001
spring:
  application:
    name: springcloud-hystrix-turbine
management:
  server:
    port: 6002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
#turbine.app-config：监控服务的服务名
turbine:
  app-config: springcloud-rest-consumer
  cluster-name-expression: new String('default')
  combine-host-port: true